import {createContext} from 'react';
import IconSearch from '@tabler/icons-react/dist/esm/icons/IconSearch.mjs';
import IconFileSearch from '@tabler/icons-react/dist/esm/icons/IconFileSearch.mjs';
import IconSettings from '@tabler/icons-react/dist/esm/icons/IconSettings.mjs';
import IconDatabase from '@tabler/icons-react/dist/esm/icons/IconDatabase.mjs';
import IconFolder from '@tabler/icons-react/dist/esm/icons/IconFolder.mjs';
import IconFolderPlus from '@tabler/icons-react/dist/esm/icons/IconFolderPlus.mjs';
import IconFileText from '@tabler/icons-react/dist/esm/icons/IconFileText.mjs';
import IconCode from '@tabler/icons-react/dist/esm/icons/IconCode.mjs';
import IconPhoto from '@tabler/icons-react/dist/esm/icons/IconPhoto.mjs';
import IconMusic from '@tabler/icons-react/dist/esm/icons/IconMusic.mjs';
import IconVideo from '@tabler/icons-react/dist/esm/icons/IconVideo.mjs';
import IconFileTypePdf from '@tabler/icons-react/dist/esm/icons/IconFileTypePdf.mjs';
import IconAdjustmentsHorizontal from '@tabler/icons-react/dist/esm/icons/IconAdjustmentsHorizontal.mjs';
import IconPlayerPause from '@tabler/icons-react/dist/esm/icons/IconPlayerPause.mjs';
import IconPlayerPlay from '@tabler/icons-react/dist/esm/icons/IconPlayerPlay.mjs';
import IconPlayerStopFilled from '@tabler/icons-react/dist/esm/icons/IconPlayerStopFilled.mjs';
import IconRefresh from '@tabler/icons-react/dist/esm/icons/IconRefresh.mjs';
import IconExternalLink from '@tabler/icons-react/dist/esm/icons/IconExternalLink.mjs';
import IconFolderOpen from '@tabler/icons-react/dist/esm/icons/IconFolderOpen.mjs';
import IconCopy from '@tabler/icons-react/dist/esm/icons/IconCopy.mjs';
import IconDots from '@tabler/icons-react/dist/esm/icons/IconDots.mjs';
import IconBolt from '@tabler/icons-react/dist/esm/icons/IconBolt.mjs';
import IconCpu from '@tabler/icons-react/dist/esm/icons/IconCpu.mjs';
import IconShieldLock from '@tabler/icons-react/dist/esm/icons/IconShieldLock.mjs';
import IconInfoCircle from '@tabler/icons-react/dist/esm/icons/IconInfoCircle.mjs';
import IconSun from '@tabler/icons-react/dist/esm/icons/IconSun.mjs';
import IconMoon from '@tabler/icons-react/dist/esm/icons/IconMoon.mjs';
import IconDeviceDesktop from '@tabler/icons-react/dist/esm/icons/IconDeviceDesktop.mjs';
import IconX from '@tabler/icons-react/dist/esm/icons/IconX.mjs';
import IconChevronDown from '@tabler/icons-react/dist/esm/icons/IconChevronDown.mjs';
import IconLoader2 from '@tabler/icons-react/dist/esm/icons/IconLoader2.mjs';
import IconAlertTriangle from '@tabler/icons-react/dist/esm/icons/IconAlertTriangle.mjs';
import IconCheck from '@tabler/icons-react/dist/esm/icons/IconCheck.mjs';
import IconPaperclip from '@tabler/icons-react/dist/esm/icons/IconPaperclip.mjs';
import IconTrash from '@tabler/icons-react/dist/esm/icons/IconTrash.mjs';
import IconArrowLeft from '@tabler/icons-react/dist/esm/icons/IconArrowLeft.mjs';
import IconActivity from '@tabler/icons-react/dist/esm/icons/IconActivity.mjs';
import IconDownload from '@tabler/icons-react/dist/esm/icons/IconDownload.mjs';
import IconArrowsHorizontal from '@tabler/icons-react/dist/esm/icons/IconArrowsHorizontal.mjs';
import IconFiles from '@tabler/icons-react/dist/esm/icons/IconFiles.mjs';
import IconClipboard from '@tabler/icons-react/dist/esm/icons/IconClipboard.mjs';
const icons={search:IconSearch,brand:IconFileSearch,settings:IconSettings,index:IconDatabase,folder:IconFolder,addFolder:IconFolderPlus,text:IconFileText,code:IconCode,image:IconPhoto,audio:IconMusic,video:IconVideo,pdf:IconFileTypePdf,filter:IconAdjustmentsHorizontal,pause:IconPlayerPause,play:IconPlayerPlay,stop:IconPlayerStopFilled,refresh:IconRefresh,open:IconExternalLink,reveal:IconFolderOpen,copy:IconCopy,more:IconDots,performance:IconBolt,cpu:IconCpu,privacy:IconShieldLock,info:IconInfoCircle,sun:IconSun,moon:IconMoon,system:IconDeviceDesktop,close:IconX,chevron:IconChevronDown,loader:IconLoader2,alert:IconAlertTriangle,check:IconCheck,attach:IconPaperclip,delete:IconTrash,back:IconArrowLeft,activity:IconActivity,export:IconDownload,resize:IconArrowsHorizontal,similar:IconFiles,paste:IconClipboard};
export type IconName=keyof typeof icons;
export type IconFamily='tabler';
export const IconTheme=createContext<'light'|'dark'>('light');
export const IconFamilyContext=createContext<IconFamily>('tabler');
export function Icon({name,size=20,className=''}:{name:IconName;size?:number;className?:string}){const Artwork=icons[name];return <Artwork size={size} stroke={2} color="currentColor" aria-hidden="true" focusable="false" className={className}/>;}
