import {useState,useEffect,useRef,type CSSProperties} from 'react';
import {listen} from '@tauri-apps/api/event';
import {open,save} from '@tauri-apps/plugin-dialog';
import {useVirtualizer} from '@tanstack/react-virtual';
import {DesignSystemProvider,Button,IconButton,PageHeader,EmptyState,Alert,ConfirmDialog,Dialog,Menu,LoadingState} from '../design-system/primitives';
import {Icon,type IconName} from '../design-system/icons';
import {command,native,bytes,type Settings,type Status,type Root,type Activity} from './api';
import {he} from '../i18n/he';import {en,type TranslationKey} from '../i18n/en';
import {SearchView} from '../features/search/SearchView';
import {SettingsView} from '../features/settings/SettingsView';
import {IndexEstimate} from '../features/index/IndexEstimate';
type Page='search'|'index'|'locations'|'activity'|'settings';
export function App(){
 const [settings,setSettings]=useState<Settings|null>(null);const [status,setStatus]=useState<Status|null>(null);const [roots,setRoots]=useState<Root[]>([]);const [activity,setActivity]=useState<Activity[]>([]);const [page,setPage]=useState<Page>('search');const [error,setError]=useState<string|null>(null);const [systemDark,setSystemDark]=useState(matchMedia('(prefers-color-scheme: dark)').matches);const quick=new URLSearchParams(location.search).has('quick');
 const [confirmation,setConfirmation]=useState<{title:string;description:string;label:string;run:()=>Promise<unknown>}|null>(null);const [busy,setBusy]=useState(false);const [report,setReport]=useState<unknown>(null);
 const t=(k:TranslationKey)=>(settings?.language==='en'?en:he)[k];const onError=(e:unknown)=>setError(String(e));
 const refresh=async()=>{const [r,a,s]=await Promise.all([command<Root[]>('get_roots'),command<Activity[]>('get_activity'),command<Status>('get_status')]);setRoots(r);setActivity(a);setStatus(s)};
 useEffect(()=>{if(!native()){setError(t('notConnectedHint'));return}const off:(()=>void)[]=[];let live=true;command<Settings>('get_settings').then(s=>{if(live)setSettings(s)}).catch(onError);void refresh().catch(onError);const retain=(f:()=>void)=>{if(live)off.push(f);else f()};void listen<Status>('index-progress',event=>{if(live)setStatus(event.payload)}).then(retain).catch(onError);void listen<Settings>('settings-changed',event=>{if(live)setSettings(event.payload)}).then(retain).catch(onError);return()=>{live=false;off.forEach(f=>f())}},[]);
 useEffect(()=>{const m=matchMedia('(prefers-color-scheme: dark)');const change=()=>setSystemDark(m.matches);m.addEventListener('change',change);return()=>m.removeEventListener('change',change)},[]);
 useEffect(()=>{document.documentElement.lang=settings?.language||'he';document.documentElement.dir=settings?.language==='en'?'ltr':'rtl'},[settings?.language]);
 useEffect(()=>{const focus=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'&&!document.querySelector('dialog[open]')){event.preventDefault();setPage('search');requestAnimationFrame(()=>document.getElementById('main-search')?.focus())}};window.addEventListener('keydown',focus);let dispose:(()=>void)|undefined;let live=true;if(native()&&!quick)void listen('search-input',()=>setPage('search')).then(f=>{if(live)dispose=f;else f()});return()=>{live=false;dispose?.();window.removeEventListener('keydown',focus)}},[]);
 useEffect(()=>{if(settings&&['locations','activity'].includes(page))void refresh().catch(onError)},[page,status?.running]);
 const act=async(action:string,args:Record<string,unknown>={})=>{setBusy(true);try{const value=await command(action,args);await refresh();return value}catch(e){onError(e);throw e}finally{setBusy(false)}};
 const selectFolders=async()=>{try{const paths=await open({directory:true,multiple:true});if(!paths)return;for(const path of typeof paths==='string'?[paths]:paths)await command('add_root',{path});await refresh();}catch(e){onError(e)}};
 const confirm=async()=>{if(!confirmation)return;setBusy(true);try{await confirmation.run();setConfirmation(null);await refresh()}catch(e){onError(e)}finally{setBusy(false)}};
 const exportReport=()=>setConfirmation({title:t('export'),description:t('exportExplain'),label:t('export'),run:async()=>{const path=await save({defaultPath:'smarti-diagnostics.json',filters:[{name:'JSON',extensions:['json']}]});if(path)await command('export_diagnostics',{path})}});
 const theme=settings?.theme==='dark'||settings?.theme==='system'&&systemDark?'dark':'light';
 return <DesignSystemProvider theme={theme} dir={settings?.language==='en'?'ltr':'rtl'} reducedMotion={Boolean(settings?.reduced_motion)}><div className={`app ${quick?'app-quick':''}`} style={{'--product-text-size':`${settings?.text_size||16}px`} as CSSProperties}>
 {!quick&&<aside className="navigation"><div className="brand"><Icon name="brand" size={32}/><span>Smarti<br/><small>Local Search</small></span></div><nav aria-label="Smarti Local Search">{(['search','index','locations','activity'] as const).map(p=><button key={p} aria-current={page===p?'page':undefined} aria-label={t(p)} className={page===p?'active':''} onClick={()=>setPage(p)}><Icon name={p==='locations'?'folder':p}/><span>{t(p)}</span></button>)}</nav><div className="nav-bottom"><span className="nav-status" role="status"><span className={`status-dot ${status?.running?'working':''}`}/>{t(status?.paused?'paused':status?.running?'working':'ready')}</span><button aria-label={t('settings')} aria-current={page==='settings'?'page':undefined} className={page==='settings'?'active':''} onClick={()=>setPage('settings')}><Icon name="settings"/><span>{t('settings')}</span></button></div></aside>}
 <main className="main"><div className="global-errors">{error&&<Alert title={error} tone="danger" action={<IconButton label={t('close')} icon="close" variant="ghost" onClick={()=>setError(null)}/>}/>}</div>
 {!settings?native()?<LoadingState label={t('loading')}/>:<EmptyState title={t('notConnected')} description={t('notConnectedHint')} icon="alert"/>:<>
 <div hidden={page!=='search'&&!quick} className="search-owner"><SearchView settings={settings} status={status} t={t} quick={quick} active={page==='search'||quick} onError={onError}/></div>
 {!quick&&page==='index'&&<section className="page index-page"><PageHeader title={t('index')} description={t('status')} actions={<><IconButton label={t(status?.paused?'resume':'pause')} icon={status?.paused?'play':'pause'} onClick={()=>void act('index_control',{control:status?.paused?'resume':'pause'}).catch(()=>{})}/><IconButton label={t('stop')} icon="stop" onClick={()=>void act('index_control',{control:'stop'}).catch(()=>{})}/><IconButton label={t('rescan')} icon="refresh" onClick={()=>void act('start_index').catch(()=>{})}/><Menu label={t('more')} items={[{id:'rebuild',label:t('rebuild'),icon:'refresh',onSelect:()=>setConfirmation({title:t('rebuild'),description:t('rebuildExplain'),label:t('confirm'),run:()=>command('rebuild_index')})},{id:'clear',label:t('clearIndex'),icon:'delete',tone:'danger',onSelect:()=>setConfirmation({title:t('clearIndex'),description:t('clearIndexExplain'),label:t('confirm'),run:()=>command('clear_index')})}]}/></>}/>
 <div className="index-summary">{([[t('metadata'),status?.files||0],[t('indexed'),status?.semantic_files||0],[t('pending'),status?.pending||0],[t('errors'),status?.errors||0]] as const).map(([label,n])=><div key={label}><strong><bdi>{n.toLocaleString()}</bdi></strong><span>{label}</span></div>)}</div>
 <div className="index-stage"><Icon name={status?.paused?'pause':status?.running?'loader':'check'}/><strong>{t(status?.paused?'paused':status?.running?'working':'ready')}</strong><span>{status?.stage==='discovery'?t('discovery'):['text','code','pdf','document','image','audio','video'].includes(status?.stage||'')?t(status!.stage as TranslationKey):''}</span></div>
 {status?.pending||status?.running&&status?.stage==='discovery'? <progress max={status.discovery_complete?status.files||1:status.discovery_total||1} value={status.discovery_counting?undefined:status.discovery_complete?Math.max(0,status.files-status.pending):status.discovery_processed||0} aria-label={t(status.discovery_complete?'indexed':'discovery')}/>:null}
 <dl className="index-info"><div><dt>{t('files')}</dt><dd><bdi>{status?.files_per_second.toFixed(1)}/s</bdi></dd></div><div><dt>{t('vectors')}</dt><dd><bdi>{status?.embeddings_per_second.toFixed(1)}/s</bdi></dd></div><div><dt>{t('bytes')}</dt><dd><bdi>{bytes(status?.bytes||0)}</bdi></dd></div></dl>
 <IndexEstimate status={status} t={t} language={settings.language}/>
 {status?.inference.error&&<Alert title={status.inference.error} tone="warning"/>}<details><summary>{t('details')}</summary><pre dir="ltr">{JSON.stringify(status,null,2)}</pre></details><div className="toolbar"><Button icon="check" loading={busy} onClick={()=>{void act('index_health').then(setReport).catch(()=>{})}}>{t('health')}</Button><Button icon="export" onClick={exportReport}>{t('export')}</Button></div>{report!==null&&<pre dir="ltr" className="diagnostics">{JSON.stringify(report,null,2)}</pre>}</section>}
 {!quick&&page==='locations'&&<section className="page"><PageHeader title={t('locations')} actions={<Button variant="primary" icon="addFolder" onClick={()=>void selectFolders()}>{t('addFolder')}</Button>}/>{!roots.length?<EmptyState title={t('noLocations')} description={t('noLocationsHint')} icon="folder"/>:<div className="location-list">{roots.map(root=><article className="location-row" key={root.id}><Icon name="folder" size={24}/><div><strong dir="ltr">{root.path}</strong><p className="sds-hint"><bdi>{root.files.toLocaleString()}</bdi> {t('files')} · <bdi>{root.indexed.toLocaleString()}</bdi> {t('indexed')}{!root.online&&` · ${t('offline')}`}</p></div><Menu label={t('more')} items={[{id:'scan',label:t('rescan'),icon:'refresh',onSelect:()=>void act('start_index',{root:root.id}).catch(()=>{})},{id:'delete',label:t('removeRoot'),icon:'delete',tone:'danger',onSelect:()=>setConfirmation({title:t('removeRoot'),description:t('removeRootExplain'),label:t('remove'),run:()=>command('remove_root',{id:root.id})})}]}/></article>)}</div>}<Button icon="play" variant="primary" disabled={!roots.length} loading={busy} onClick={()=>void act('start_index').catch(()=>{})}>{t('start')}</Button></section>}
 {!quick&&page==='activity'&&<section className="page activity-page"><PageHeader title={t('activity')} actions={<><IconButton label={t('refresh')} icon="refresh" onClick={()=>void refresh().catch(onError)}/><IconButton label={t('export')} icon="export" onClick={exportReport}/></>}/><ActivityList items={activity} t={t} onRetry={id=>void act('retry',{id}).catch(()=>{})}/></section>}
 {!quick&&page==='settings'&&<SettingsView settings={settings} status={status} t={t} onSave={setSettings} onError={onError}/>}
 {!settings.onboarded&&!quick&&<Onboarding error={error} settings={settings} roots={roots} status={status} t={t} onFolders={selectFolders} refresh={refresh} onError={onError} onFinish={setSettings}/>}
 </>}
 </main><ConfirmDialog open={Boolean(confirmation)} title={confirmation?.title||''} description={confirmation?.description||''} confirmLabel={confirmation?.label||t('confirm')} onConfirm={()=>void confirm()} onClose={()=>setConfirmation(null)} busy={busy} error={error||undefined}/></div></DesignSystemProvider>
}
function ActivityList({items,t,onRetry}:{items:Activity[];t:(k:TranslationKey)=>string;onRetry:(id:number)=>void}){const parent=useRef<HTMLDivElement>(null);const list=useVirtualizer({count:items.length,getScrollElement:()=>parent.current,estimateSize:()=>112,overscan:4});return <div ref={parent} className="activity-scroll">{!items.length?<EmptyState title={t('noActivity')} description={t('noActivityHint')} icon="activity"/>:<div style={{height:list.getTotalSize(),position:'relative'}}>{list.getVirtualItems().map(v=>{const item=items[v.index];return <article key={item.id} className="activity-row" style={{height:v.size,position:'absolute',top:0,width:'100%',transform:`translateY(${v.start}px)`}}><Icon name={item.kind==='error'||item.kind==='partial'?'alert':'check'}/><div><strong dir="auto">{item.message}</strong><p className="sds-hint" dir="ltr">{item.path}</p><small><bdi>{new Date(item.time*1000).toLocaleString()}</bdi></small></div>{item.file_id!==null&&<IconButton label={t('retry')} icon="refresh" onClick={()=>onRetry(item.file_id!)}/>}</article>})}</div>}</div>}
function Onboarding({settings,roots,status,t,onFolders,refresh,onError,onFinish,error}:{settings:Settings;roots:Root[];status:Status|null;t:(k:TranslationKey)=>string;onFolders:()=>Promise<void>;refresh:()=>Promise<void>;onError:(e:unknown)=>void;onFinish:(s:Settings)=>void;error:string|null}){
 const [step,setStep]=useState(0);const [busy,setBusy]=useState(false);
 const choose=async(entire:boolean)=>{setBusy(true);try{const paths=await command<string[]>('initial_locations',{entire});if(!paths.length)throw new Error(t('noLocationsHint'));for(const root of roots){if(!paths.includes(root.path))await command('remove_root',{id:root.id})}for(const path of paths){if(!roots.some(r=>r.path===path))await command('add_root',{path})}}catch(e){onError(e)}finally{await refresh().catch(onError);setBusy(false)}};
 const remove=async(id:number)=>{setBusy(true);try{await command('remove_root',{id});await refresh()}catch(e){onError(e)}finally{setBusy(false)}};
 const finish=async()=>{setBusy(true);try{const s=await command<Settings>('update_settings',{settings:{...settings,onboarded:true}});await command('start_index');onFinish(s)}catch(e){onError(e)}finally{setBusy(false)}};
 return <Dialog open title="Smarti Local Search" dismissible={false} onClose={()=>{}}><div className="onboarding"><Icon name={step===0?'brand':step===1?'folder':step===2?'cpu':'search'} size={48}/><h2>{t((['welcome','scope','performanceWelcome','begin'] as const)[step])}</h2>{error&&<Alert title={error} tone="danger"/>}{step===0&&<p>{t('welcomePrivacy')}</p>}{step===1&&<><div className="onboarding-options"><Button icon="folder" loading={busy} onClick={()=>void choose(false)}>{t('recommended')}</Button><Button icon="system" loading={busy} onClick={()=>void choose(true)}>{t('entire')}</Button><Button icon="addFolder" disabled={busy} onClick={()=>void onFolders()}>{t('custom')}</Button></div><p className="sds-hint">{t('scopeHint')}</p><ul className="onboarding-roots">{roots.map(r=><li key={r.id}><bdi>{r.path}</bdi><IconButton label={t('removeRoot')} icon="close" disabled={busy} onClick={()=>void remove(r.id)}/></li>)}</ul></>}{step===2&&<><p>{status?.inference.ready?<bdi>{status.inference.backend?.toUpperCase()}</bdi>:status?.inference.error||t('loading')}</p><p className="sds-hint">{t('benchmarkHint')}</p></>}<div className="onboarding-footer">{step>0&&<Button disabled={busy} onClick={()=>setStep(step-1)}>{t('back')}</Button>}<Button variant="primary" disabled={step===1&&!roots.length} loading={busy} onClick={()=>step===3?void finish():setStep(step+1)}>{t(step===3?'finish':'next')}</Button></div></div></Dialog>
}
