; Tauri-specific installer messages; standard NSIS Hebrew strings come from MUI2.
LangString addOrReinstall ${LANG_HEBREW} "הוספה / התקנה מחדש של רכיבים"
LangString alreadyInstalled ${LANG_HEBREW} "התוכנה כבר מותקנת"
LangString alreadyInstalledLong ${LANG_HEBREW} "${PRODUCTNAME} ${VERSION} כבר מותקנת. בחר את הפעולה הרצויה ולחץ הבא."
LangString appRunning ${LANG_HEBREW} "${PRODUCTNAME} פועלת. סגור אותה ונסה שוב."
LangString appRunningOkKill ${LANG_HEBREW} "${PRODUCTNAME} פועלת!$\nלחץ אישור כדי לסגור אותה."
LangString chooseMaintenanceOption ${LANG_HEBREW} "בחר את פעולת התחזוקה הרצויה."
LangString choowHowToInstall ${LANG_HEBREW} "בחר כיצד להתקין את ${PRODUCTNAME}."
LangString createDesktop ${LANG_HEBREW} "יצירת קיצור דרך בשולחן העבודה"
LangString dontUninstall ${LANG_HEBREW} "ללא הסרת ההתקנה"
LangString dontUninstallDowngrade ${LANG_HEBREW} "ללא הסרת ההתקנה (התקנת גרסה ישנה דורשת הסרה תחילה)"
LangString failedToKillApp ${LANG_HEBREW} "לא ניתן לסגור את ${PRODUCTNAME}. סגור אותה ונסה שוב."
LangString installingWebview2 ${LANG_HEBREW} "מתקין את WebView2..."
LangString newerVersionInstalled ${LANG_HEBREW} "גרסה חדשה יותר של ${PRODUCTNAME} כבר מותקנת. מומלץ להסיר אותה לפני התקנת גרסה ישנה. בחר את הפעולה הרצויה ולחץ הבא."
LangString older ${LANG_HEBREW} "ישנה יותר"
LangString olderOrUnknownVersionInstalled ${LANG_HEBREW} "מותקנת גרסה $R4 של ${PRODUCTNAME}. מומלץ להסיר אותה לפני ההתקנה. בחר את הפעולה הרצויה ולחץ הבא."
LangString silentDowngrades ${LANG_HEBREW} "לא ניתן להתקין גרסה ישנה במצב שקט. הפעל את אשף ההתקנה.$\n"
LangString unableToUninstall ${LANG_HEBREW} "לא ניתן להסיר את ההתקנה."
LangString uninstallApp ${LANG_HEBREW} "הסרת ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_HEBREW} "הסרת ההתקנה הקיימת תחילה"
LangString unknown ${LANG_HEBREW} "לא ידועה"
LangString webview2AbortError ${LANG_HEBREW} "התקנת WebView2 נכשלה. התוכנה דורשת רכיב זה. נסה להפעיל שוב את המתקין."
LangString webview2DownloadError ${LANG_HEBREW} "הורדת WebView2 נכשלה: $0"
LangString webview2DownloadSuccess ${LANG_HEBREW} "מתקין WebView2 הורד בהצלחה"
LangString webview2Downloading ${LANG_HEBREW} "מוריד את מתקין WebView2..."
LangString webview2InstallError ${LANG_HEBREW} "התקנת WebView2 נכשלה עם קוד $1"
LangString webview2InstallSuccess ${LANG_HEBREW} "WebView2 הותקן בהצלחה"
LangString deleteAppData ${LANG_HEBREW} "מחיקת נתוני התוכנה"
