import {useEffect,useRef,useState,useMemo} from 'react';
import {useVirtualizer} from '@tanstack/react-virtual';
import {convertFileSrc} from '@tauri-apps/api/core';
import {getCurrentWebview} from '@tauri-apps/api/webview';
import {listen} from '@tauri-apps/api/event';
import {open} from '@tauri-apps/plugin-dialog';
import {Button,IconButton,Menu,EmptyState,Field,SelectField,Alert} from '../../design-system/primitives';
import {Icon,type IconName} from '../../design-system/icons';
import {bytes,timestamp,command,search,native,type Settings,type Status,type Result,type Preview} from '../../app/api';
import type {TranslationKey} from '../../i18n/en';
type T=(key:TranslationKey)=>string;
const fileIcon=(kind:string):IconName=>(({document:'text',binary:'text'} as Record<string,string>)[kind] as IconName)||(['text','code','image','audio','video','pdf'].includes(kind)?kind as IconName:'text');
export function SearchView({settings,status,t,quick=false,active=true,onError}:{settings:Settings;status:Status|null;t:T;quick?:boolean;active?:boolean;onError:(e:unknown)=>void}){
 const [query,setQuery]=useState('');const [media,setMedia]=useState<string|null>(null);const [mode,setMode]=useState(settings.default_mode);const [advanced,setAdvanced]=useState(false);
 const [kind,setKind]=useState('');const [extension,setExtension]=useState('');const [path,setPath]=useState('');const [after,setAfter]=useState('');const [results,setResults]=useState<Result[]>([]);const [selected,setSelected]=useState<number|null>(null);const [preview,setPreview]=useState<Preview|null>(null);const [busy,setBusy]=useState(false);const [warning,setWarning]=useState<string|null>(null);const [sort,setSort]=useState('relevance');const [submitted,setSubmitted]=useState(0);const [elapsed,setElapsed]=useState<number|null>(null);
 const input=useRef<HTMLInputElement>(null);const scroll=useRef<HTMLDivElement>(null);const serial=useRef(0);const previewSerial=useRef(0);const [previewWidth,setPreviewWidth]=useState(420);
 const acceptedSubmission=useRef({number:0,query:''});
 const mediaPlayer=useRef<HTMLMediaElement|null>(null);const [pdfPage,setPdfPage]=useState(1);const [pdf,setPdf]=useState<{asset:string;page:number;count:number}|null>(null);
 useEffect(()=>{setPdf(null);if(preview?.file.kind!=='pdf')return;let live=true;void command<{asset:string;page:number;count:number}>('pdf_page',{id:preview.file.id,page:pdfPage}).then(value=>{if(live)setPdf(value)}).catch(onError);return()=>{live=false}},[preview?.file.id,pdfPage]);
 const sorted=useMemo(()=>{const out=[...results];if(sort==='name')out.sort((a,b)=>a.file.name.localeCompare(b.file.name));if(sort==='modified')out.sort((a,b)=>b.file.modified-a.file.modified);if(sort==='size')out.sort((a,b)=>b.file.size-a.file.size);return quick?out.slice(0,8):out},[results,sort,quick]);
 const virtual=useVirtualizer({count:sorted.length,getScrollElement:()=>scroll.current,estimateSize:()=>112,overscan:5});
 const filters=useMemo(()=>({...(kind?{kind}:{}),...(extension?{extension}:{}),...(path?{path}:{}),...(after?{after:Math.floor(new Date(after).getTime()/1000)}:{})}),[kind,extension,path,after]);
 const applyInput=(value:{query?:string;media?:string|null})=>{setQuery(value.query||'');setMedia(value.media||null);setSubmitted(x=>x+1);input.current?.focus();};
 useEffect(()=>{if(!native())return;let off:(()=>void)[]=[];let alive=true;Promise.all([listen<{query?:string;media?:string}>('search-input',e=>applyInput(e.payload)),listen('quick-open',()=>{applyInput({});setPreview(null);setSelected(null);}),getCurrentWebview().onDragDropEvent(e=>{if(e.payload.type==='drop'){setMedia(e.payload.paths[0]);setSubmitted(x=>x+1);}})]).then(async list=>{if(alive){off=list;if(!quick){const initial=await command<{query?:string;media?:string}|null>('initial_input');if(initial&&alive)applyInput(initial)}}else list.forEach(f=>f())}).catch(onError);return()=>{alive=false;off.forEach(f=>f())}},[]);
 useEffect(()=>{const token=++serial.current;const id=Date.now()*1000+token;let timer:ReturnType<typeof setTimeout>|undefined;let stopped=false;
  if(!query.trim()&&!media&&!Object.keys(filters).length){setResults([]);setBusy(false);setWarning(null);acceptedSubmission.current={number:submitted,query:''};return}
  if(!settings.search_as_you_type&&submitted===acceptedSubmission.current.number&&query!==acceptedSubmission.current.query)return;
  acceptedSubmission.current={number:submitted,query};
  setBusy(true);setWarning(null);const base={id,query,mode,filters,media};
  search({...base,semantic_pass:false}).then(r=>{if(serial.current!==token||stopped)return;setResults(r.results);setElapsed(r.elapsed_ms);setSelected(old=>r.results.some(x=>x.file.id===old)?old:r.results[0]?.file.id??null);if(mode==='exact'){setBusy(false)}}).catch(e=>{if(serial.current===token){onError(e);setBusy(false)}});
  if(mode!=='exact')timer=setTimeout(()=>{search({...base,semantic_pass:true}).then(r=>{if(serial.current!==token||stopped)return;setResults(r.results);setElapsed(r.elapsed_ms);setWarning(r.warning);setSelected(old=>r.results.some(x=>x.file.id===old)?old:r.results[0]?.file.id??null)}).catch(e=>{if(serial.current===token)onError(e)}).finally(()=>{if(serial.current===token)setBusy(false)})},125);
  return()=>{stopped=true;clearTimeout(timer);void command('cancel_search',{id}).catch(()=>{})};
 },[query,media,mode,filters,submitted,settings.search_as_you_type,settings.dimensions,settings.results_count,settings.show_offline]);
 const action=(action:string,id:number)=>command(action,{id}).catch(onError);
 const showPreview=async(result:Result)=>{setSelected(result.file.id);const token=++previewSerial.current;try{const p=await command<Preview>('get_preview',{id:result.file.id});if(previewSerial.current===token){setPdfPage(result.matches[0]?.page||1);setPreview(p)}}catch(e){onError(e)}};
 const choose=async()=>{try{const file=await open({multiple:false,directory:false});if(typeof file==='string'){setMedia(file);setSubmitted(x=>x+1);}}catch(e){onError(e)}};
 const paste=async()=>{try{const file=await command<string>('clipboard_image');setMedia(file);setSubmitted(x=>x+1)}catch(e){onError(e)}};
 useEffect(()=>{if(!active)return;const keys=(e:KeyboardEvent)=>{const typing=e.target instanceof HTMLInputElement||e.target instanceof HTMLSelectElement||e.target instanceof HTMLTextAreaElement;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();input.current?.focus();return}if(e.key==='Escape'){if(document.querySelector('dialog[open],[role="menu"]'))return;if(preview){setPreview(null);previewSerial.current++;}else if(quick){void command('hide_quick').catch(onError)}return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='v'&&e.shiftKey){e.preventDefault();void paste();return}
   if(['ArrowDown','ArrowUp'].includes(e.key)&&(!typing||e.target===input.current)){e.preventDefault();const i=sorted.findIndex(r=>r.file.id===selected);const next=Math.max(0,Math.min(sorted.length-1,i+(e.key==='ArrowDown'?1:-1)));if(sorted[next]){setSelected(sorted[next].file.id);virtual.scrollToIndex(next,{align:'auto'})}}
   if(e.key==='Enter'&&e.target===input.current&&!settings.search_as_you_type){e.preventDefault();setSubmitted(x=>x+1);return}
   if(e.key==='Enter'&&selected!==null&&(!typing||e.target===input.current)){e.preventDefault();const result=sorted.find(r=>r.file.id===selected);if(!result)return;if(quick&&e.ctrlKey){void command('show_main',{query,media}).then(()=>command('hide_quick')).catch(onError)}else if(e.shiftKey){void action('reveal_path',selected)}else if(settings.enter_preview){void showPreview(result)}else{void action('open_path',selected)}}
   if(e.key===' '&&!typing&&selected!==null){e.preventDefault();const result=sorted.find(r=>r.file.id===selected);if(result)void showPreview(result)}};window.addEventListener('keydown',keys);return()=>window.removeEventListener('keydown',keys)},[active,sorted,selected,preview,query,media,settings.enter_preview,settings.search_as_you_type]);
 return <section className={`search-page ${quick?'quick-page':''}`} aria-label={t('search')}>
 {quick&&<div data-tauri-drag-region className="quick-dragbar"/>}
 <div className="search-header"><div className="search-box"><Icon name="search" size={24}/><label className="sds-visually-hidden" htmlFor="main-search">{t('search')}</label><input id="main-search" ref={input} value={query} placeholder={t('placeholder')} autoFocus dir="auto" onChange={e=>setQuery(e.target.value)} onPaste={e=>{if([...e.clipboardData.items].some(i=>i.type.startsWith('image/'))){e.preventDefault();void paste()}}}/><div className="search-actions"><IconButton label={t('attach')} icon="attach" variant="ghost" onClick={()=>void choose()}/>{(query||media)&&<IconButton label={t('clear')} icon="close" variant="ghost" onClick={()=>{setQuery('');setMedia(null)}}/>}<IconButton label={t('filter')} icon="filter" variant="ghost" aria-expanded={advanced} onClick={()=>setAdvanced(!advanced)}/>{quick&&<IconButton label={t('close')} icon="close" variant="ghost" onClick={()=>void command('hide_quick').catch(onError)}/>}</div></div>
 <div className="search-meta"><Menu label={t(mode as TranslationKey)} fitContent items={(['smart','semantic','exact'] as const).map(m=>({id:m,label:t(m),onSelect:()=>setMode(m)}))}><span>{t(mode as TranslationKey)}</span></Menu>{media&&<button className="chip" onClick={()=>setMedia(null)}><Icon name="attach"/><bdi dir="ltr">{media.split(/[\\/]/).pop()}</bdi><Icon name="close"/></button>}{kind&&<button className="chip" onClick={()=>setKind('')}>{t(kind as TranslationKey)}<Icon name="close"/></button>}{extension&&<button className="chip" onClick={()=>setExtension('')}>{extension}<Icon name="close"/></button>}{path&&<button className="chip" onClick={()=>setPath('')}><bdi dir="ltr">{path}</bdi><Icon name="close"/></button>}{after&&<button className="chip" onClick={()=>setAfter('')}>{after}<Icon name="close"/></button>}{Object.keys(filters).length>0&&<Button variant="ghost" onClick={()=>{setKind('');setExtension('');setPath('');setAfter('')}}>{t('clearFilters')}</Button>}<span className="search-feedback" role="status">{busy?t('semanticPending'):elapsed!==null?<bdi>{sorted.length} · {elapsed.toFixed(0)} ms</bdi>:''}</span></div>
 {advanced&&<div className="filter-panel"><SelectField label={t('type')} value={kind} onChange={e=>setKind(e.target.value)}><option value="">{t('all')}</option>{['text','code','pdf','document','image','audio','video','binary'].map(k=><option key={k} value={k}>{t(k as TranslationKey)}</option>)}</SelectField><Field label={t('extension')} value={extension} onChange={e=>setExtension(e.target.value)} dir="ltr"/><Field label={t('path')} value={path} onChange={e=>setPath(e.target.value)} dir="ltr"/><Field label={t('after')} type="date" value={after} onChange={e=>setAfter(e.target.value)}/><p className="sds-hint" dir="auto">{t('syntax')}</p></div>}
 {warning&&<Alert title={warning} tone="warning"/>}</div>
 <div className="search-body"> <div className="result-area">{sorted.length>0&&!quick&&<div className="result-tools"><SelectField label={t('sort')} hiddenLabel value={sort} onChange={e=>setSort(e.target.value)}>{['relevance','name','modified','size'].map(k=><option value={k} key={k}>{t(k as TranslationKey)}</option>)}</SelectField></div>}
 <div ref={scroll} className="result-scroll" role="listbox" aria-label={t('search')} tabIndex={0} aria-activedescendant={selected!==null?`result-${selected}`:undefined}>
 {!sorted.length?<EmptyState icon="search" title={query||media?t('noResults'):t('empty')} description={query||media?t('noResultsHint'):t('emptyHint')}/>:<div style={{height:virtual.getTotalSize(),position:'relative'}}>{virtual.getVirtualItems().map(item=>{const r=sorted[item.index],c=r.matches[0];return <article id={`result-${r.file.id}`} key={r.file.id} role="option" aria-selected={selected===r.file.id} className="result-row" style={{position:'absolute',top:0,insetInlineStart:0,width:'100%',height:item.size,transform:`translateY(${item.start}px)`}} onClick={()=>void showPreview(r)} onDoubleClick={()=>void action('open_path',r.file.id)}>
 <div className="result-icon"><Icon name={fileIcon(r.file.kind)} size={24}/></div><div className="result-text"><strong dir="auto">{r.file.name}</strong>{c?.text&&<div className="excerpt" dir="auto">{highlight(c.text.slice(0,220),r.lexical>0?query:'')}</div>}<div className="result-path"><bdi dir="ltr">{r.file.path}</bdi></div><div className="result-caption"><bdi>{bytes(r.file.size)} · {new Date(r.file.modified*1000).toLocaleDateString(settings.language)}</bdi>{c?.page&&<bdi> · p. {c.page}</bdi>}{c?.line_start&&<bdi> · {c.line_start}–{c.line_end}</bdi>}{c?.start!==null&&c?.start!==undefined&&<bdi> · {timestamp(c.start)}</bdi>}{!r.file.online&&<span>{t('offline')}</span>}</div></div>
 <div className="result-actions" onClick={e=>e.stopPropagation()}><IconButton label={t('open')} icon="open" variant="ghost" onClick={()=>void action('open_path',r.file.id)} tooltip={false}/><Menu label={t('more')} items={[{id:'reveal',label:t('reveal'),icon:'reveal',onSelect:()=>void action('reveal_path',r.file.id)},{id:'copy',label:t('copy'),icon:'copy',onSelect:()=>void action('copy_path',r.file.id)},{id:'similar',label:t('similar'),icon:'similar',onSelect:()=>{setMedia(r.file.path);setMode('smart');setSubmitted(x=>x+1)}},{id:'retry',label:t('retry'),icon:'refresh',onSelect:()=>void action('retry',r.file.id)}]}/></div></article>})}</div>}
 </div>{!query&&!media&&status&&<p className="index-footnote"><bdi>{status.files.toLocaleString()}</bdi> {t('metadata')} · {t(status.paused?'paused':status.running?'working':'ready')}</p>}</div>
 {preview&&<><div className="preview-divider" role="separator" aria-label={t('preview')} aria-orientation="vertical" tabIndex={0} onKeyDown={e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const change=(e.key==='ArrowLeft'?-24:24)*(settings.language==='he'?-1:1);setPreviewWidth(w=>Math.max(280,Math.min(640,w+change)))}}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);const origin=e.clientX;const width=previewWidth;const move=(event:PointerEvent)=>setPreviewWidth(Math.max(280,Math.min(640,width+(settings.language==='he'?-1:1)*(event.clientX-origin))));const done=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',done)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',done)}}/>
 <aside className="preview-panel" style={{width:previewWidth}} aria-label={t('preview')}><div className="preview-toolbar"><strong dir="auto">{preview.file.name}</strong><IconButton label={t('open')} icon="open" variant="ghost" onClick={()=>void action('open_path',preview.file.id)}/><IconButton label={t('reveal')} icon="reveal" variant="ghost" onClick={()=>void action('reveal_path',preview.file.id)}/><IconButton label={t('copy')} icon="copy" variant="ghost" onClick={()=>void action('copy_path',preview.file.id)}/><IconButton label={t('close')} icon="close" variant="ghost" onClick={()=>{setPreview(null);previewSerial.current++}}/></div><div className="preview-content">
 {preview.asset&&preview.file.kind==='image'&&<img src={convertFileSrc(preview.asset)} alt={preview.file.name}/>}
 {preview.file.kind==='pdf'&&(pdf?<div><img src={convertFileSrc(pdf.asset)} alt={`${t('pdf')} ${pdf.page}`}/><div className="sds-actions"><Button disabled={pdf.page<=1} onClick={()=>setPdfPage(pdf.page-1)}>{t('back')}</Button><bdi>{pdf.page} / {pdf.count}</bdi><Button disabled={pdf.page>=pdf.count} onClick={()=>setPdfPage(pdf.page+1)}>{t('next')}</Button></div></div>:<p role="status">{t('loading')}</p>)}
 {preview.asset&&['audio','video'].includes(preview.file.kind)&&(preview.file.kind==='audio'?<audio ref={element=>{mediaPlayer.current=element}} key={preview.asset} controls src={`${convertFileSrc(preview.asset)}#t=${results.find(r=>r.file.id===preview.file.id)?.matches[0]?.start||0}`}/>:<video ref={element=>{mediaPlayer.current=element}} key={preview.asset} controls src={`${convertFileSrc(preview.asset)}#t=${results.find(r=>r.file.id===preview.file.id)?.matches[0]?.start||0}`}/>)}
 {preview.file.kind==='code'?<pre dir="ltr">{preview.text}</pre>:<div className="preview-text" dir="auto">{preview.text}</div>}
 <details open><summary>{t('matches')}</summary>{(results.find(r=>r.file.id===preview.file.id)?.matches||preview.chunks).slice(0,50).map(c=><div key={c.id} className="match-passage">{c.page&&<bdi>p. {c.page} · </bdi>}{c.start!==null&&<Button variant="ghost" icon="play" onClick={()=>{const player=mediaPlayer.current;if(player){player.currentTime=c.start||0;void player.play().catch(onError)}}}><bdi>{timestamp(c.start)}{c.end!==null?` – ${timestamp(c.end)}`:""}</bdi></Button>}{c.heading&&<strong dir="auto">{c.heading}</strong>}<p dir={c.modality==='code'?'ltr':'auto'}>{c.text.slice(0,1200)}</p></div>)}</details><p className="sds-hint" dir="ltr">{preview.file.path}</p>{settings.debug_logging&&<pre dir="ltr">{JSON.stringify(results.find(r=>r.file.id===preview.file.id),null,2)}</pre>}</div></aside></>}
 </div></section>
}
export function highlight(text:string,query:string){const words=query.match(/[\p{L}\p{N}]{2,}/gu)||[];if(!words.length)return text;const escaped=words.map(w=>w.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'));const regex=new RegExp(`(${escaped.join('|')})`,'gi');return text.split(regex).map((part,i)=>i%2?<mark key={i}>{part}</mark>:part);}
