export const en={
 excludeFolder:'Exclude folder',excludeFile:'Exclude file',exclusionHint:'Global exclusions for all locations: one folder name, pattern, or full path per line. Folder paths exclude their contents. Choose folders or files below. Changes are saved automatically.',invalidSetting:'Enter a value within the allowed range.',
 discoveryRemaining:'File discovery: estimated time remaining',indexRemaining:'Content indexing: estimated time remaining',estimating:'Estimating…',afterDiscovery:'Estimate available after discovery',estimatePaused:'Available when indexing resumes',complete:'Complete',estimateProvisional:'Initial estimate. It will adjust as each file type is processed.',estimateHint:'Estimate based on measured speed; file sizes and media can change it.',
 moveIndex:'Move index storage',moveExplain:'Indexing will stop. The validated index will be copied to the selected folder, and the app will restart. The original copy is retained.',
 search:'Search',index:'Index',locations:'Locations',activity:'Activity',settings:'Settings',
 placeholder:'Search all your files…',empty:'Find it by meaning, name, content or image',emptyHint:'Ctrl+K to search · Ctrl+Alt+Space for Quick Search',noResults:'No matching files',noResultsHint:'Try different words or remove a filter.',
 smart:'Smart',semantic:'Semantic',exact:'Exact',filter:'Filters',attach:'Search using a file',clear:'Clear',open:'Open',reveal:'Show in Explorer',copy:'Copy path',more:'More actions',similar:'Find similar files',close:'Close',back:'Back',
 type:'Type',extension:'Extension',path:'Location',after:'Modified after',before:'Modified before',size:'Size',all:'All',clearFilters:'Clear filters',preview:'Preview',matches:'More matches in this file',offline:'Offline',ready:'Ready',loading:'Preparing the search engine…',semanticPending:'Completing semantic search…',
 text:'Text',code:'Code',document:'Office documents',pdf:'PDF',image:'Images',audio:'Audio',video:'Video',binary:'Other files',
 addFolder:'Add folder',addDrive:'Add drive',removeRoot:'Remove location',removeRootExplain:'Remove this location and its indexed data? The original files stay on disk.',exclusions:'Exclusions',edit:'Edit',save:'Save',cancel:'Cancel',confirm:'Confirm',
 start:'Start indexing',pause:'Pause',resume:'Resume',stop:'Stop',rescan:'Rescan',rebuild:'Rebuild index',rebuildExplain:'Rebuild the index for your selected locations? Search will become available as files are processed.',clearIndex:'Clear index',clearIndexExplain:'Remove all indexed content? Your files and configured locations stay on disk.',compact:'Compact index',health:'Check index health',details:'Technical details',files:'Files',vectors:'Vectors',errors:'Errors',pending:'Pending',indexed:'Semantically indexed',metadata:'Available to search',retry:'Retry',export:'Export diagnostics',exportExplain:'The report includes file paths and technical errors. Review it before sharing.',noActivity:'No recent activity',noActivityHint:'Indexing events and files needing attention appear here.',
 general:'General',appearance:'Appearance',performance:'Performance',storage:'Storage',windows:'Windows integration',privacy:'Privacy',advanced:'Advanced',about:'About',privacyText:'All search and indexing happen on your computer. No uploads, accounts, cloud APIs or telemetry.',privacyIndex:'The index can contain extracted text. Treat it as private data and store it in a private folder.',
 language:'Language',theme:'Theme',system:'System',light:'Light',dark:'Dark',reduced:'Reduce motion',textSize:'Text size',autostart:'Start with Windows',tray:'Continue in the system tray when closing',quick:'Global Quick Search',shortcut:'Global shortcut',explorer:'Explorer context menu',notifications:'Notify when initial indexing finishes',mode:'Default search mode',count:'Result limit',asYouType:'Search as you type',enterPreview:'Enter opens preview',showOffline:'Show files on disconnected drives',profile:'Performance profile',auto:'Automatic',quiet:'Quiet',balanced:'Balanced',fast:'Fast',accelerator:'Text accelerator',threads:'CPU thread limit',benchmark:'Run performance test',benchmarkHint:'Capabilities are enabled only after successful local inference.',dimensions:'Vector quality',dimensionExplain:'Changing semantic settings requires re-indexing all semantic content. Lexical search remains available.',maxText:'Maximum text size (MB)',cacheLimit:'Cache limit (MB)',keepReady:'Keep search ready in memory',network:'Allow network locations',battery:'Pause heavy media indexing on battery',sensitive:'Include sensitive files',sensitiveHint:'Includes credentials, .env and private key files. The index is private data, not a security boundary.',audioSeconds:'Audio segment (seconds)',videoSeconds:'Video segment (seconds)',videoFps:'Video frames per second',visionTokens:'Vision token budget',debug:'Technical diagnostics',reset:'Reset settings',resetExplain:'Restore default app settings? Your indexed locations and files remain available.',licenses:'Third-party licenses',licenseHint:'EmbeddingGemma 2 and LiteRT: Apache 2.0 · Tabler: MIT · FFmpeg: LGPL · PDFium: BSD. See bundled notices for complete terms.',
 welcome:'Search by meaning, not just by name.',welcomePrivacy:'Your files stay on your computer.',next:'Continue',scope:'What would you like to index?',recommended:'My files',entire:'Entire computer',custom:'Choose folders',scopeHint:'System caches, dependency folders and sensitive files are excluded by default.',performanceWelcome:'Finding the best local search engine',begin:'Your files become searchable while indexing continues.',finish:'Start searching',selected:'Selected locations',status:'Index status',discovery:'Discovering files',paused:'Paused',working:'Indexing',notConnected:'Native service unavailable',notConnectedHint:'Start this interface using the Tauri desktop application.',sort:'Sort',relevance:'Relevance',name:'Name',modified:'Modified',duplicates:'Find duplicates',none:'None',model:'Model',version:'Version',dataPath:'Index directory',bytes:'Storage',refresh:'Refresh',remove:'Remove',noLocations:'Choose where to search',noLocationsHint:'Add folders or drives to build your private local index.',syntax:'Examples: type:pdf · ext:rs · path:"C:\\Projects" · size:>10MB',checkComplete:'Health check result',
} as const;
export type TranslationKey=keyof typeof en;
