import {useState,useEffect} from 'react';
import {open} from '@tauri-apps/plugin-dialog';
import {Button,SettingRow,Switch,SelectField,Field,SettingsGroup,ConfirmDialog,Alert} from '../../design-system/primitives';
import {command,type Settings,type Status,bytes} from '../../app/api';
import type {TranslationKey} from '../../i18n/en';
import {useSettingsAutosave} from './useSettingsAutosave';
import {ExclusionEditor} from './ExclusionEditor';
type T=(k:TranslationKey)=>string;
const categories=['general','search','index','performance','storage','appearance','windows','privacy','advanced','about'] as const;
export function SettingsView({settings,status,t,onSave,onError}:{settings:Settings;status:Status|null;t:T;onSave:(s:Settings)=>void;onError:(e:unknown)=>void}){
 const autosave=useSettingsAutosave(settings,onSave,onError);const {draft,update}=autosave;
 const [numbers,setNumbers]=useState<Partial<Record<keyof Settings,string>>>({});
 const [localError,setLocalError]=useState<string|undefined>();const reportError=(e:unknown)=>{setLocalError(String(e));onError(e)};const [category,setCategory]=useState<typeof categories[number]>('general');const [busy,setBusy]=useState(false);const [confirm,setConfirm]=useState<'reset'|'move'|null>(null);const [report,setReport]=useState<unknown>(null);const [destination,setDestination]=useState('');const [storagePath,setStoragePath]=useState('');
 useEffect(()=>{if(category==='storage')void command<{path:string}>('storage_info').then(r=>setStoragePath(r.path)).catch(reportError)},[category]);
 const chooseStorage=async()=>{try{const path=await open({directory:true,multiple:false});if(typeof path==='string'){setDestination(path);setConfirm('move')}}catch(e){reportError(e)}};
 const toggle=(key:keyof Settings,label:TranslationKey,hint?:TranslationKey)=><SettingRow title={t(label)} description={hint?t(hint):undefined}><Switch label={t(label)} checked={Boolean(draft[key])} onCheckedChange={v=>update(key,v)}/></SettingRow>;
 const number=(key:keyof Settings,label:TranslationKey,min:number,max:number,step=1)=>{const value=numbers[key]??String(draft[key]);const n=Number(value),invalid=value===''||!Number.isFinite(n)||n<min||n>max||Math.abs((n-min)/step-Math.round((n-min)/step))>1e-6;return <SettingRow title={t(label)}><Field label={t(label)} hiddenLabel type="number" required min={min} max={max} step={step} value={value} error={invalid?t('invalidSetting'):undefined} onChange={e=>{setNumbers(v=>({...v,[key]:e.target.value}));update(key,e.target.value===''?NaN:e.target.valueAsNumber)}}/></SettingRow>};
 const select=(key:keyof Settings,label:TranslationKey,options:[string,string][])=><SettingRow title={t(label)}><SelectField label={t(label)} hiddenLabel value={String(draft[key])} onChange={e=>update(key,key==='dimensions'?Number(e.target.value):e.target.value)}>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</SelectField></SettingRow>;
 const run=async(action:string)=>{setBusy(true);try{setReport(await command(action))}catch(e){reportError(e)}finally{setBusy(false)}};
 return <div className="settings-page"><nav className="settings-nav" aria-label={t('settings')}>{categories.map(c=><button className={category===c?'active':''} key={c} onClick={()=>{setCategory(c);setReport(null)}}>{t(c)}</button>)}</nav><div className="settings-content"><h1>{t(category)}</h1><SettingsGroup title={t(category)} variant="plain" hideHeader>
 {category==='general'&&select('language','language',[['he','עברית'],['en','English']])}
 {category==='search'&&<>{select('default_mode','mode',['smart','semantic','exact'].map(v=>[v,t(v as TranslationKey)]))}{number('results_count','count',1,500)}{toggle('search_as_you_type','asYouType')}{toggle('enter_preview','enterPreview')}{toggle('show_offline','showOffline')}</>}
 {category==='index'&&<>{(['text','code','documents','images','audio','video'] as const).map(k=><div key={k}>{toggle(k,(({documents:'document',images:'image'} as Record<string,string>)[k]||k) as TranslationKey)}</div>)}{toggle('pause_on_battery','battery')}{toggle('network_drives','network')}<ExclusionEditor value={draft.exclusions} onChange={v=>update('exclusions',v)} t={t} onError={reportError}/></>}
 {category==='performance'&&<>{select('profile','profile',['auto','quiet','balanced','fast'].map(v=>[v,t(v as TranslationKey)]))}{select('accelerator','accelerator',[['auto',t('auto')],['cpu','CPU'],['gpu','GPU'],['npu','NPU']])}{number('threads','threads',1,128)}{toggle('keep_ready','keepReady')}<p className="sds-hint">{t('benchmarkHint')}</p><Button icon="performance" loading={busy} onClick={()=>void run('benchmark')}>{t('benchmark')}</Button><Button icon="cpu" onClick={()=>void run('hardware')}>{t('details')}</Button>{status?.inference.backend&&<p><bdi>Text: {status.inference.backend.toUpperCase()} · Vision: CPU · Audio: CPU</bdi></p>}</>}
 {category==='storage'&&<>{select('dimensions','dimensions',[['128','Compact · 128'],['256','Balanced · 256'],['512','Quality · 512'],['768','Maximum · 768']])}{number('max_text_mb','maxText',1,512)}{number('cache_mb','cacheLimit',32,8192)}<SettingRow title={t('dataPath')}><bdi>{storagePath}</bdi></SettingRow><Button icon="folder" onClick={()=>void chooseStorage()}>{t('moveIndex')}</Button><SettingRow title={t('bytes')}><bdi>{bytes(status?.bytes||0)}</bdi></SettingRow><Button icon="index" loading={busy} onClick={()=>void run('compact_index')}>{t('compact')}</Button><Button icon="check" onClick={()=>void run('index_health')}>{t('health')}</Button></>}
 {category==='appearance'&&<>{select('theme','theme',['system','light','dark'].map(v=>[v,t(v as TranslationKey)]))}{number('text_size','textSize',13,24)}{toggle('reduced_motion','reduced')}</>}
 {category==='windows'&&<>{toggle('quick_search','quick')}<SettingRow title={t('shortcut')}><Field label={t('shortcut')} hiddenLabel dir="ltr" value={draft.shortcut} onChange={e=>update('shortcut',e.target.value)}/></SettingRow>{toggle('autostart','autostart')}{toggle('minimize_to_tray','tray')}{toggle('explorer_menu','explorer')}{toggle('notifications','notifications')}</>}
 {category==='privacy'&&<><Alert title={t('privacyText')}/><p>{t('privacyIndex')}</p>{toggle('sensitive_files','sensitive','sensitiveHint')}</>}
 {category==='advanced'&&<>{number('audio_seconds','audioSeconds',10,120)}{number('video_seconds','videoSeconds',10,60)}{number('video_fps','videoFps',0.1,4,0.1)}{number('vision_tokens','visionTokens',70,1120)}{toggle('debug_logging','debug')}<Button variant="danger" onClick={()=>setConfirm('reset')}>{t('reset')}</Button></>}
 {category==='about'&&<><p>Smarti Local Search · {__APP_VERSION__}</p><p>EmbeddingGemma 2 · 740M · LiteRT-LM 0.18.0</p><p>{t('privacyText')}</p><h2>{t('licenses')}</h2><p>{t('licenseHint')}</p><Button icon="info" onClick={()=>void run('third_party_notices')}>{t('details')}</Button></>}
 </SettingsGroup>{(autosave.error||localError)&&<Alert title={autosave.error||localError!} tone="danger"/>}{report!==null&&<pre dir="ltr" className="diagnostics">{typeof report==='string'?report:JSON.stringify(report,null,2)}</pre>}</div>
 <ConfirmDialog error={localError} open={confirm==='move'} title={t('moveIndex')} description={`${t('moveExplain')} ${destination}`} confirmLabel={t('confirm')} busy={busy} onConfirm={()=>{setBusy(true);void command('move_index',{path:destination}).catch(reportError).finally(()=>setBusy(false))}} onClose={()=>setConfirm(null)}/>
 <ConfirmDialog error={autosave.error} open={autosave.semanticPending} title={t('dimensions')} description={t('dimensionExplain')} confirmLabel={t('confirm')} busy={autosave.busy} onConfirm={()=>void autosave.confirmSemantic()} onClose={()=>{autosave.cancelSemantic();setNumbers({})}}/>
 <ConfirmDialog error={localError} open={confirm==='reset'} title={t('reset')} description={t('resetExplain')} confirmLabel={t('confirm')} busy={autosave.busy} onConfirm={()=>{void autosave.reset().then(()=>{setNumbers({});setConfirm(null)}).catch(reportError)}} onClose={()=>setConfirm(null)}/></div>
}
